[PT-186] Signup form endpoint
0xbase-Corp/portfolio_svc pull request #53
Opened 2024-05-27 08:03 UTC by 0xbuilder0

# [PT-186](https://0xbase.atlassian.net/browse/PT-186) - Signup form endpoint

### Description

2024-05-27 08:44 UTC, 0xbuilder0 commented
TODO: swagger docs

2024-05-28 16:11 UTC, 0xbuilder0 commented
> TODO: swagger docs

DONE

2024-05-31 18:51 UTC, fuddin95 approved these changes

2024-05-31 18:51 UTC, fuddin95 commented on internal/routes/portfolios.go
> +	v1.GET("/portfolio/solana", middlewares.VerifyToken(), func(c *gin.Context) { controllers.SolanaController(c, db) })
Please group middleware like so https://gin-gonic.com/docs/examples/using-middleware/

2024-05-31 18:51 UTC, fuddin95 commented on shared/utils/generate-token.go
> +	return generateToken(userID, 12*time.Minute)
Please create a const something `ACCESS_TOKEN_EXPIRY`  & `REFRESH_TOKEN_EXPIRY`

2024-05-31 18:52 UTC, fuddin95 requested changes
Ping once done

2024-05-31 19:33 UTC, 0xbuilder0 commented on shared/utils/generate-token.go
> +	return generateToken(userID, 12*time.Minute)
done

2024-05-31 19:39 UTC, 0xbuilder0 commented on internal/routes/portfolios.go
> +	v1.GET("/portfolio/solana", middlewares.VerifyToken(), func(c *gin.Context) { controllers.SolanaController(c, db) })
done

2024-05-31 19:48 UTC, fuddin95 commented on internal/routes/portfolios.go
> +	auth := router.Group("/api/v1/auth")
we just keep the path `"/api/v1"` no need for "auth"

2024-05-31 20:01 UTC, fuddin95 approved these changes

2024-05-31 20:05 UTC, 0xbuilder0 commented on internal/routes/portfolios.go
> +	auth := router.Group("/api/v1/auth")
just group the routes like signup and signin is group by `/api/v1/auth/XXXX` same for portfolios like `/api/v1/portfolios/XXXX`  and for bundles like `/api/v1/bundles/XXXX`

2024-05-31 20:05 UTC, merged